### ISSUE TITLE
carbon-prometheus-metrics milliseconds don't make sense

### ISSUE THREAD

**Issue by passingBySol** [sevenlabs-hq/carbon#85]
## problem 
it's great that we have a default implementation for metrics, esp. the prometheus crate is super helpful.
yet the `process_time` timers are not really helpful. 

those are measured in milliseconds and at least on my machine (mbp m2max), when listening for raydium, i always hit < 1 ms. 
<img width="614" alt="image" src="https://github.com/user-attachments/assets/51c3624b-f460-428b-a259-f23924bb1eca">

since parsing yellowstone updates is pretty cheap (???) i guess we can switch to using nanosecs? 

## proposed solution
1. we can capture these metrics in both ms and ns
2. make unit of measurement configurable using a builder pattern when initializing `PrometheusMetrics` from a predefined enum?

**Comment by KellianDev** [comment]
Thanks for the issue. You're right that millisecond precision isn't always sufficient.

It's important to know that the metrics implementation is abstracted behind the `Metrics` trait, which is implementation-agnostic. That means `PrometheusMetrics` itself is not responsible for the unit of time being recorded.

I think whether we should record milliseconds or nanoseconds depend on the datasource and on the processor. Some datasources like `carbon-yellowstone-grpc-datasource` would benefit from having times recorded in nanoseconds whilst some like `carbon-transaction-crawler-datasource` make the most sense with milliseconds.

That means, we should simply review the implementation of each datasource and change the recording to nanoseconds when it makes the most sense.

As of the regular `updates_processing_times`, I think it would make sense here to also record nanoseconds since it should support the use of any `Processor` implementation, with some potentially being very fast and some being slow (with IO operations for example). 

So what I propose is the following:
1. Core Pipeline (`crates/core/pipeline.rs`):
   - Rename `updates_processing_times` to `updates_process_time_milliseconds`.
   - Add `updates_process_time_nanoseconds` metrics.

3. Datasource-specific implementations:
   - `carbon-yellowstone-grpc-datasource`: Switch to nanoseconds
   - `carbon-rpc-program-subscribe-datasource`: Switch to nanoseconds
   - `carbon-rpc-block-subscribe-datasource`: Switch to nanoseconds
   - `carbon-helius-atlas-ws-datasource`: Switch to nanoseconds 

I don't believe it's necessary to make this configurable, especially since it would mean adding the configuration to each datasource and it would require anyone that wants to publish a datasource to take it into account, when in reality they probably know best about the unit of time that makes the most sense for their implementation.

Let me know what you think.

We have other pending changes for `carbon-core`. So if that sounds good to you, I'll bundle this improvement with them in a new version release by Thursday.

Assigning myself this issue.
